#living-room
#bed-room1
#bed-room2
substitutions:
  devicename: radar-test
  address_name: radar-test
  topicradargpio: radar/test/gpioout
  project_name: $devicename

esphome:
  name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  networks:
    - ssid: !secret ssid1
      password: !secret ssid1_password
  ap:
    ssid: ${devicename}
    password: sm123456
    ap_timeout: 2min
  use_address: $address_name
  fast_connect: False
  power_save_mode: none
  domain: .local

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: !secret mqtt_port
  discovery: True
  discovery_retain: True
  discovery_prefix: homeassistant #homeassistant
  topic_prefix: 'radar/test'

captive_portal:

ota:
  password: !secret ota_password

# api:
#   password: !secret api_password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_password

# Enable logging
logger:
  level: INFO
  # baud_rate: 0
  baud_rate: 115200

uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart

sensor:
  - platform: wifi_signal
    name: $project_name RSSI
    update_interval: 60s
  - platform: uptime
    name: $project_name Uptime Sensor
    id: uptime_sensor
    update_interval: 3600s
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

binary_sensor:
  - platform: ld2410
    has_target:
      name: $project_name LD Presence
    has_moving_target:
      name: $project_name LD Moving Target
    has_still_target:
      name: $project_name LD Still Target

switch:
  - platform: ld2410
    engineering_mode:
      name: $project_name LD Engineering Mode
    bluetooth:
      name: $project_name LD Control Bluetooth

button:
  - platform: restart
    name: $project_name Restart
    entity_category: config
  - platform: factory_reset
    disabled_by_default: True
    name: $project_name Factory Reset
    id: factory_reset_all

text_sensor:
  - platform: template
    name: $project_name Uptime
    id: uptime_human
    icon: mdi:clock-start
  - platform: wifi_info
    ip_address:
      name: $project_name IP Address

light:
  - platform: binary
    name: $project_name RunLed
    id: radar_test_runled
    internal: true
    output: radar_test_run_led

output:
  - platform: gpio
    id: radar_test_run_led
    pin: GPIO14
    inverted: true
